-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 15:30:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EventsDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EventsDB` ;

-- -----------------------------------------------------
-- Schema EventsDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EventsDB` DEFAULT CHARACTER SET utf8 ;
USE `EventsDB` ;

-- -----------------------------------------------------
-- Table `EventsDB`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EventsDB`.`User` ;

CREATE TABLE IF NOT EXISTS `EventsDB`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventsDB`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EventsDB`.`Event` ;

CREATE TABLE IF NOT EXISTS `EventsDB`.`Event` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `bbox` POLYGON NULL,
  `organisationName` VARCHAR(45) NULL,
  `creatorID` INT NOT NULL COMMENT 'Event Creator',
  `description` TEXT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `fk_Event_Usert1_idx` (`creatorID` ASC) VISIBLE,
  UNIQUE INDEX `eventID_UNIQUE` (`eventID` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_Event_User Account1`
    FOREIGN KEY (`creatorID`)
    REFERENCES `EventsDB`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventsDB`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EventsDB`.`Activity` ;

CREATE TABLE IF NOT EXISTS `EventsDB`.`Activity` (
  `activityID` INT NOT NULL AUTO_INCREMENT,
  `centreLocation` POINT NOT NULL,
  `polygonLocation` POLYGON NOT NULL,
  `bbox` POLYGON NOT NULL,
  `description` TEXT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `name` VARCHAR(45) NOT NULL,
  `eventID` INT NOT NULL,
  `locationName` VARCHAR(45) NULL,
  `backgroundPicture` BLOB NULL,
  `creatorID` INT NOT NULL,
  PRIMARY KEY (`activityID`),
  INDEX `fk_Activity_Event1_idx` (`eventID` ASC) VISIBLE,
  INDEX `fk_Activity_User1_idx` (`creatorID` ASC) VISIBLE,
  UNIQUE INDEX `activityID_UNIQUE` (`activityID` ASC) VISIBLE,
  CONSTRAINT `fk_Activity_Event1`
    FOREIGN KEY (`eventID`)
    REFERENCES `EventsDB`.`Event` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activity_User Account1`
    FOREIGN KEY (`creatorID`)
    REFERENCES `EventsDB`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventsDB`.`Visit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EventsDB`.`Visit` ;

CREATE TABLE IF NOT EXISTS `EventsDB`.`Visit` (
  `time` DATETIME NULL,
  `userID` INT NOT NULL,
  `activityID` INT NOT NULL,
  PRIMARY KEY (`userID`, `activityID`),
  INDEX `fk_Visit_Activity1_idx` (`activityID` ASC) VISIBLE,
  CONSTRAINT `fk_Visit_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `EventsDB`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Activity1`
    FOREIGN KEY (`activityID`)
    REFERENCES `EventsDB`.`Activity` (`activityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EventsDB`.`Joined Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EventsDB`.`Joined Events` ;

CREATE TABLE IF NOT EXISTS `EventsDB`.`Joined Events` (
  `userID` INT NOT NULL,
  `eventID` INT NOT NULL,
  PRIMARY KEY (`userID`, `eventID`),
  INDEX `fk_User Account_has_Event_Event1_idx` (`eventID` ASC) VISIBLE,
  INDEX `fk_User Account_has_Event_User Account1_idx` (`userID` ASC) VISIBLE,
  CONSTRAINT `fk_User Account_has_Event_User Account1`
    FOREIGN KEY (`userID`)
    REFERENCES `EventsDB`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User Account_has_Event_Event1`
    FOREIGN KEY (`eventID`)
    REFERENCES `EventsDB`.`Event` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
